# Plotly Express

Check the presentation blog post [Introducing Plotly Express](https://medium.com/@plotlygraphs/introducing-plotly-express-808df010143d).

In [ ]:
# Plotly Express is now a sublibrary of Plotly:
import plotly.express as px

## Tidy DataFrames as input in Plotly Express

Tidy Data according to Hadley Wickham: ([original paper](http://vita.had.co.nz/papers/tidy-data.pdf))

- Each variable forms a column and contains values
- Each observation forms a row
- Each type of observational unit forms a table

In [ ]:
import pandas as pd

In [ ]:
# Here is a "messy" dataframe (wide-form):
messy = pd.DataFrame({
    'patient': ['John Smith', 'Jane Doe', 'Mary Johnson'],
    'Treatment A': [None, 16, 3],
    'Treatment B': [2, 11, 1],
})

messy

In [ ]:
# The pandas method `.melt` can often be used to tidy the data (long-form):
tidy = messy.melt(
    id_vars=['patient'],
    value_vars=['Treatment A', 'Treatment B'],
    var_name='Treatment',
    value_name='Result',
)

tidy

In [ ]:
# Once it is in tidy format, plotly express allows you to build complex interactive plots with a one-liner:
px.bar(
    data_frame=tidy,
    x='patient',
    y='Result',
    color='Treatment',
    barmode='group',
    title='Medical Treatment Results',
)

**IMPORTANT**: From Plotly.py version 4.8 it is no longer a requirement to use [tidy](https://www.jeannicholashould.com/tidy-data-in-python.html) dataframes. See [this post](https://medium.com/plotly/beyond-tidy-plotly-express-now-accepts-wide-form-and-mixed-form-data-bdc3e054f891).

In [ ]:
# Plotly express also takes messy dataframes (suitable for quick visualizations during data exploration).
px.bar(
    messy, 
    x='patient', 
    y=['Treatment A', 'Treatment B'], 
    barmode='group',
    title='Medical Treatment Results',
)

## Exercise 1

Use the example cluster data, loaded with:

In [1]:
import pandas as pd
table = pd.read_csv('https://raw.githubusercontent.com/chumo/Data2Serve/master/transition_clusters.csv')

In [2]:
table.head()

           Xi          Yi          Xf          Yf color
0  109.360643  434.557514   90.755847  171.363051   red
1   55.957358  438.934136   84.189607  182.890903   red
2  369.115969  419.904538  112.121845  144.288556   red
3  491.392739  492.316412  116.747266  170.049756   red
4   34.286602  404.017801   97.938407  181.777689   red

In [6]:
result = pd.concat([
    table[['Xi', 'Yi', 'color']].assign(status='Initial').rename(columns={'Xi': 'x', 'Yi': 'y'}),
    table[['Xf', 'Yf', 'color']].assign(status='Final').rename(columns={'Xf': 'x', 'Yf': 'y'}),
], ignore_index=True)

result.head()

            x           y color   status
0  109.360643  434.557514   red  Initial
1   55.957358  438.934136   red  Initial
2  369.115969  419.904538   red  Initial
3  491.392739  492.316412   red  Initial
4   34.286602  404.017801   red  Initial

... and convert it into a tidy dataframe (_HINT_: use `pd.concat` method). It should look like this:

![](images/fig_05.0.png)

## Exercise 2

In [9]:
import plotly.express as px
import pandas as pd

fig = px.bar(
    data_frame=result,
    x=result.x,
    y=result.y,
    color=result.color,
    barmode='group',
    title='Medical Treatment Results',
)

fig

Take the tidy dataframe created in Exercise 1 and build this plot with two subplots:

![](images/fig_05.1.png)

Check the docs:

- [plotly express scatter](https://plotly.com/python-api-reference/generated/plotly.express.scatter)
  - range_x
  - range_y
  - facet_row
  - labels
  - color
  - color_discrete_map
  - facet_row_spacing
  
After the figure has been created, you can hide the legend with:

`.update_layout(showlegend=False)`

And now try to make each subplot as a frame of an animated plot:

![](images/fig_05.2.png)

Check the docs:

- [plotly express scatter](https://plotly.com/python-api-reference/generated/plotly.express.scatter)
  - animation_frame
  - category_orders

## Exercise 3

Using the gapminder data:

In [ ]:
gapminder = px.data.gapminder()

In [ ]:
gapminder.head()

Build the following plot:

![](images/fig_05.3.png)

Check the docs:

- [plotly express choropleth](http://plotly.com/python-api-reference/generated/plotly.express.choropleth)
  - locations

And now the following plot:

![](images/fig_05.4.png)

Check the docs:

- [plotly express box](https://plotly.com/python-api-reference/generated/plotly.express.box.html)
  - points

## Plotly Express powered backend for Pandas plotting

Since Pandas 0.25 it is possible to provide any backend for the `.plot` plotting API. 

Plotly backend ([see here](https://plotly.com/python/pandas-backend/)) can be set with:

In [ ]:
import pandas as pd
pd.options.plotting.backend = 'plotly'

Then you can use the most common functionalities of Plotly Express by passing your Plotly parameters to the `.plot` method available to any pandas DataFrame;

In [ ]:
tidy.plot.bar(
    x='patient', 
    y='Result', 
    color='Treatment',
    barmode='group',
    title='Medical Treatment Results',
)